image:
  repository: localhost:32000/geekweek/talos-discovery-service
  pullPolicy: Always
  tag: "latest"

gc_interval: 60
listen_port: 3000
loglevel: talos_discovery_service=debug
ingress: nginx # nginx | traefik
ingress_route: /talosdiscovery
