{{ if eq .Values.ingress "nginx" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talos-discovery-service-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress_route }}
        pathType: Prefix
        backend:
          service:
            name: talos-discovery-service
            port:
              number: {{ .Values.listen_port }}
{{ else }}
{{- fail "no or invalid ingress type set in .Values.ingress" }}
{{ end }}
